---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: 이 섹션에서는 Dremio 인증에 사용되는 하드웨어와 소프트웨어에 대해 설명합니다.  이 정보는 NetApp 스토리지를 사용한 Dremio 배포에 적용할 수 있습니다. 
---
= 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
하이브리드 아이스버그 레이크하우스 솔루션은 데이터 레이크 고객이 직면한 과제를 해결하는 데 고유한 이점을 제공합니다.  Dremio Unified Lakehouse 플랫폼과 NetApp ONTAP, StorageGRID, NetApp Cloud 솔루션을 활용하면 회사는 비즈니스 운영에 상당한 가치를 더할 수 있습니다.  이 솔루션은 NetApp 소스를 포함한 여러 데이터 소스에 대한 액세스를 제공할 뿐만 아니라 전반적인 분석 성능을 향상시키고 회사가 비즈니스 성장으로 이어지는 비즈니스 통찰력을 얻는 데 도움을 줍니다.



== NetApp 개요

* ONTAP 및 StorageGRID 와 같은 NetApp의 제품은 스토리지와 컴퓨팅을 분리하여 특정 요구 사항에 따라 최적의 리소스 활용을 가능하게 합니다.  이러한 유연성 덕분에 고객은 NetApp 스토리지 솔루션을 사용하여 스토리지를 독립적으로 확장할 수 있습니다.
* NetApp의 스토리지 컨트롤러를 활용하면 고객은 NFS 및 S3 프로토콜을 사용하여 벡터 데이터베이스에 효율적으로 데이터를 제공할 수 있습니다.  이러한 프로토콜은 고객 데이터 저장을 용이하게 하고 벡터 데이터베이스 인덱스를 관리하며, 파일 및 객체 메서드를 통해 액세스하는 여러 데이터 사본의 필요성을 제거합니다.
* NetApp ONTAP AWS, Azure, Google Cloud 등 주요 클라우드 서비스 공급업체에서 NAS 및 개체 스토리지에 대한 기본 지원을 제공합니다.  이러한 광범위한 호환성은 원활한 통합을 보장하여 고객 데이터 이동성, 글로벌 접근성, 재해 복구, 동적 확장성 및 고성능을 구현합니다.




=== StorageGRID

업계를 선도하는 당사 객체 스토리지 storageGRID는 자동화된 데이터 배치를 위한 강력한 정책 엔진, 유연한 배포 옵션, 계층적 삭제 코딩을 통한 탁월한 내구성을 제공합니다.  단일 네임스페이스에서 수십억 개의 객체와 페타바이트 규모의 데이터를 지원하는 확장 가능한 아키텍처를 갖추고 있습니다.  이 솔루션은 하이브리드 클라우드 통합을 지원하여 주요 클라우드 플랫폼으로 데이터를 계층화할 수 있습니다.  2019 IDC Marketscape Worldwide Object-Based Vendor Assessment에서 리더로 인정받았습니다.

또한, storageGRID는 소프트웨어 정의 객체 스토리지, 지리적 중복성, 다중 사이트 기능을 통해 대규모 비정형 데이터를 관리하는 데 탁월합니다.  정책 기반 정보 수명 주기 관리를 통합하고 미러링 및 검색과 같은 클라우드 통합 기능을 제공합니다.  Common Criteria, NF203 디지털 금고 부품, ISO/IEC 25051, KPMG, Cohasset 규정 준수 평가를 포함한 다양한 인증을 받았습니다.

요약하자면, NetApp storageGRID는 대규모 비정형 데이터를 효율적으로 관리하는 데 필요한 강력한 기능, 확장성, 하이브리드 클라우드 통합 및 규정 준수 인증을 제공합니다.



=== NetApp ONTAP

NetApp ONTAP 은 광범위한 엔터프라이즈 기능을 제공하는 강력한 스토리지 솔루션입니다.  여기에는 애플리케이션 일관적이고 변조 방지된 즉각 백업을 제공하는 스냅샷이 포함되어 있습니다.  SnapRestore 필요에 따라 백업을 거의 즉시 복원할 수 있게 해주는 반면, SnapMirror 통합된 원격 백업 및 재해 복구 기능을 제공합니다.  이 솔루션은 다중 관리자 검증, FIPS 인증을 통한 저장 데이터 암호화, 전송 중 데이터 암호화, 다중 요소 인증(MFA), 역할 기반 액세스 제어(RBAC)와 같은 기능으로 데이터 보안을 보장하는 자율형 랜섬웨어 보호(ARP) 기능도 통합합니다.  포괄적인 로깅, 감사, 온보딩 및 외부 키 관리, 안전한 정리, 여러 테넌트의 안전한 관리를 통해 데이터 보안과 규정 준수가 더욱 강화됩니다.

NetApp ONTAP 또한 낮은 총소유비용으로 높은 수준의 무결성, 성능 및 보존을 제공하는 규정을 준수하는 데이터 보존 기능을 제공하는 SnapLock 기능을 갖추고 있습니다.  NetApp ONTAP 9와 완벽하게 통합되어 악의적인 행위, 사기성 관리자 및 랜섬웨어로부터 보호 기능을 제공합니다.

이 솔루션은 전송 중 및 저장 데이터 암호화를 위한 NSE/NVE 암호화, 다중 관리자 액세스, 다중 관리자 검증을 포함합니다.  Active IQ AI 기반 예측 분석과 시정 조치를 제공하고, QoS는 서비스 품질 워크로드 제어를 보장합니다.  관리 및 자동화 통합은 SysMgr/GUI/CLI/API를 통해 직관적으로 이루어집니다.  FabricPool 자동 데이터 계층화를 지원하고, 해당 솔루션은 인라인 데이터 압축, 중복 제거 및 압축을 통해 효율성을 제공합니다.  NetApp 고객에게 추가 비용 없이 워크로드 효율성 목표 달성을 보장합니다.

NetApp ONTAP NVMe/FC, FC, NVMe/TCP, iSCSI, NFS, SMB, S3 등 다양한 프로토콜을 지원하여 통합 스토리지 솔루션을 제공합니다.  전반적으로 NetApp ONTAP 다양한 스토리지 요구 사항을 충족하는 광범위한 엔터프라이즈 기능, 강력한 보안, 규정 준수, 효율성 및 다용성을 제공합니다.



== 드레미오 개요

Dremio는 셀프서비스 분석 및 AI를 위한 통합 레이크하우스 플랫폼입니다.  Dremio 통합 분석 플랫폼은 기존 데이터웨어하우스 솔루션 비용의 일부만으로 레이크하우스의 유연성, 확장성 및 성능을 제공하여 사용자가 데이터에 더욱 가까이 접근할 수 있도록 합니다.  Dremio는 복잡하고 비용이 많이 드는 데이터 통합 및 ETL을 없애는 "시프트-레프트" 분석을 지원하여 데이터 이동 없이 원활한 엔터프라이즈 규모 분석을 제공합니다.  Dremio의 또 다른 특징은 다음과 같습니다.

* 범용 의미 계층과 긴밀하게 통합된 고성능 SQL 쿼리 엔진을 통해 사용하기 쉬운 셀프 서비스 분석이 가능하므로 클라우드와 온프레미스 모두에서 모든 데이터를 보다 쉽게 연결, 관리 및 분석할 수 있습니다.
* Dremio의 Apache Iceberg 기반 레이크하우스 관리 기능은 데이터 검색을 간소화하고, 데이터 최적화를 자동화하며, Git에서 영감을 받은 데이터 버전 관리를 통해 고성능 분석을 제공합니다.
* 오픈 소스와 개방형 표준을 기반으로 구축된 Dremio는 기업이 특정 분야에 얽매이지 않고 혁신을 위한 입지를 유지할 수 있도록 지원합니다.  대기업들은 Dremio를 모든 워크로드에 걸쳐 가장 가격 대비 성능이 뛰어나고 사용하기 가장 쉬운 레이크하우스 플랫폼으로 신뢰합니다.




== Dremio와 NetApp Hybrid Iceberg Lakehouse 솔루션은 고객에게 어떤 가치를 제공합니까?

* *향상된 데이터 관리 및 접근성*: Dremio는 조직이 데이터 레이크에서 고속으로 직접 데이터를 쿼리할 수 있도록 하는 데이터 레이크하우스 플랫폼으로 잘 알려져 있습니다.  반면, NetApp 클라우드 데이터 서비스와 데이터 저장 솔루션 분야의 선두주자입니다.  이 공동 제안은 고객에게 기업의 데이터를 효율적이고 효과적으로 저장, 관리, 액세스 및 분석할 수 있는 포괄적인 솔루션을 제공합니다.
* *성능 최적화*: NetApp의 데이터 스토리지 전문성과 Dremio의 데이터 처리 및 데이터 최적화 역량을 바탕으로, 이 파트너십은 데이터 운영의 성능을 개선하고, 대기 시간을 줄이고, 비즈니스 통찰력을 얻는 속도를 높여주는 솔루션을 제공합니다.  Dremio는 NetApp의 내부 IT 분석 인프라에도 성능상의 이점을 제공했습니다.
* *확장성*: Dremio와 NetApp 모두 확장 가능하도록 설계된 솔루션을 제공합니다.  이 공동 솔루션은 고객에게 확장성이 뛰어난 데이터 저장, 데이터 관리 및 분석 환경을 제공합니다.  하이브리드 Iceberg Lakehouse 환경에서 Dremio SQL 쿼리 엔진은 NetApp StorageGRID 와 결합되어 모든 비즈니스의 분석 요구 사항을 처리할 수 있는 탁월한 확장성, 동시성 및 쿼리 성능을 제공합니다.
* *데이터 보안 및 거버넌스*: 두 회사 모두 데이터 보안과 거버넌스에 중점을 두고 있습니다.  이 두 가지 솔루션을 함께 사용하면 강력한 보안 및 데이터 거버넌스 기능을 제공하여 데이터가 보호되고 데이터 거버넌스 요구 사항이 충족되도록 할 수 있습니다.  역할 기반 및 세분화된 액세스 제어, 포괄적인 감사, 종단 간 데이터 계보, 통합 ID 관리, 광범위한 규정 준수 및 보안 프레임워크를 갖춘 SSO와 같은 기능을 통해 회사의 분석 데이터 환경이 안전하고 관리되도록 보장합니다.
* *비용 효율성*: Dremio의 데이터 레이크 엔진을 NetApp의 스토리지 솔루션과 통합함으로써 고객은 데이터 관리 및 데이터 이동과 관련된 비용을 줄일 수 있습니다.  조직은 기존 데이터 레이크 환경에서 NetApp 과 Dremio로 구성된 보다 현대적인 레이크하우스 솔루션으로 전환할 수도 있습니다.  이 하이브리드 Iceberg Lakehouse 솔루션은 고속 쿼리 성능과 시장 선도적인 쿼리 동시성을 제공하여 TCO를 낮추고 비즈니스 통찰력을 얻는 시간을 단축합니다.

