---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-overview.html 
keywords: storagegrid, splunk enterprise, smartstore, object storage, machine data 
summary: 이 페이지에서는 NetApp StorageGRID, Splunk Enterprise, Splunk SmartStore를 비롯하여 이 솔루션을 완성하는 데 사용된 구성 요소에 대해 설명합니다. 
---
= 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 NetApp StorageGRID, Splunk Enterprise, Splunk SmartStore를 비롯하여 이 솔루션을 완성하는 데 사용된 구성 요소에 대해 설명합니다.



== NetApp StorageGRID

NetApp StorageGRID 는 고성능이고 비용 효율적인 객체 스토리지 플랫폼입니다.  분산형 노드 기반 그리드 아키텍처를 사용하여 지능적이고 정책 기반의 글로벌 데이터 관리를 제공합니다.  유비쿼터스 글로벌 객체 네임스페이스와 정교한 데이터 관리 기능을 결합하여 페타바이트 규모의 비정형 데이터와 수십억 개의 객체를 간편하게 관리할 수 있습니다.  단일 호출 객체 액세스는 여러 사이트로 확장되어 고가용성 아키텍처를 단순화하는 동시에 사이트나 인프라 중단에 관계없이 지속적인 객체 액세스를 보장합니다.

멀티테넌시를 통해 여러 클라우드 및 엔터프라이즈 비정형 데이터 애플리케이션을 동일한 그리드 내에서 안전하게 서비스할 수 있어 StorageGRID 의 ROI와 사용 사례가 늘어납니다.  메타데이터 기반 개체 수명 주기 정책을 사용하면 여러 서비스 수준을 생성하여 여러 지역에 걸쳐 내구성, 보호, 성능 및 지역성을 최적화할 수 있습니다.  사용자는 요구 사항이 변경됨에 따라 중단 없이 정책을 조정하고 데이터 환경을 재정비할 수 있습니다.

SmartStore는 원격 스토리지 계층으로 StorageGRID 활용하고 고객이 지리적으로 분산된 여러 사이트를 배포하여 강력한 가용성과 내구성을 확보할 수 있도록 하며, 이는 단일 개체 네임스페이스로 제공됩니다.  이를 통해 Splunk SmartStore는 StorageGRID 의 고성능, 고밀도 용량, 단일 URL을 사용하여 여러 물리적 사이트에 걸쳐 수백 개의 노드로 확장하는 기능을 활용하여 개체와 상호 작용할 수 있습니다.  이 단일 URL을 사용하면 단일 사이트를 넘어서도 중단 없이 저장소 확장, 업그레이드 및 수리를 수행할 수 있습니다.  StorageGRID 의 고유한 데이터 관리 정책 엔진은 최적화된 수준의 성능과 내구성을 제공하며 데이터 지역성 요구 사항을 준수합니다.



== 스플렁크 엔터프라이즈

기계에서 생성된 데이터의 수집 및 분석 분야를 선도하는 Splunk는 운영 분석 기능을 통해 IT를 간소화하고 현대화하는 데 도움을 줍니다.  또한 비즈니스 분석, 보안, IoT 사용 사례로 확장됩니다.  스토리지는 Splunk 소프트웨어를 성공적으로 배포하는 데 중요한 요소입니다.

기계에서 생성된 데이터는 가장 빠르게 성장하는 빅데이터 유형입니다.  이 형식은 예측 불가능하며 다양한 출처에서 나오는 경우가 많고, 종종 빠른 속도로 대량으로 발생합니다.  이러한 작업 부하 특성은 종종 디지털 배기라고 불립니다.  Splunk SmartStore는 이러한 데이터를 이해하는 데 도움이 되며, 가장 비용 효율적인 스토리지 계층에 핫 데이터와 웜 데이터를 최적으로 배치하기 위한 스마트한 데이터 계층화를 제공합니다.



== 스플렁크 스마트스토어

Splunk SmartStore는 StorageGRID 와 같은 개체 스토리지(원격 스토리지 또는 원격 스토리지 계층이라고도 함)를 사용하여 S3 프로토콜을 사용하여 웜 데이터를 저장하는 인덱서 기능입니다.

배포된 데이터 볼륨이 증가함에 따라 일반적으로 저장소에 대한 수요가 컴퓨터 리소스에 대한 수요를 앞지릅니다.  SmartStore를 사용하면 컴퓨팅과 스토리지를 별도로 확장하여 인덱서 스토리지와 컴퓨팅 리소스를 비용 효율적으로 관리할 수 있습니다.

SmartStore는 S3 프로토콜과 캐시 관리자를 사용하여 원격 스토리지 계층을 도입했습니다.  이러한 기능을 사용하면 데이터를 인덱서나 원격 저장소에 로컬로 저장할 수 있습니다.  인덱서에 있는 캐시 관리자는 인덱서와 원격 스토리지 계층 간의 데이터 이동을 관리합니다.  데이터는 버킷 메타데이터와 함께 버킷(핫 및 웜)에 저장됩니다.

SmartStore를 사용하면 인덱서 저장소 공간을 최소한으로 줄이고 대부분의 데이터가 원격 저장소 계층에 있으므로 I/O 최적화된 컴퓨팅 리소스를 선택할 수 있습니다.  인덱서는 요청되고 예측된 결과를 반환하는 데 필요한 최소한의 데이터 양을 나타내는 로컬 캐시를 유지 관리합니다.  로컬 캐시에는 핫 버킷, 활성 또는 최근 검색에 참여하는 웜 버킷의 사본 및 버킷 메타데이터가 포함되어 있습니다.

StorageGRID 탑재된 Splunk SmartStore를 사용하면 고객은 고성능 및 비용 효율적인 원격 스토리지를 통해 환경을 점진적으로 확장할 수 있으며, 동시에 전체 솔루션에 높은 수준의 탄력성을 제공합니다.  이를 통해 고객은 더 많은 인덱서가 필요하거나, 데이터 보존 기간을 변경하거나, 중단 없이 수집 속도를 높여야 하는 경우, 언제든지 원하는 수량만큼 구성 요소(핫 스토리지 및/또는 웜 S3 스토리지)를 추가할 수 있습니다.
