---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-benefits.html 
keywords: benefits, performance, multi-site, scalability, capacity, availability, cache 
summary: 이 솔루션을 사용하면 단일 및 다중 사이트 배포에서 사용자 수나 수집 속도 측면에서 증가하는 수요를 충족하기 위해 컴퓨팅, 핫 스토리지 또는 S3 리소스를 추가할 수 있습니다. 
---
= 이 솔루션의 이점
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 솔루션을 사용하면 단일 및 다중 사이트 배포에서 사용자 수나 수집 속도 측면에서 증가하는 수요를 충족하기 위해 컴퓨팅, 핫 스토리지 또는 S3 리소스를 추가할 수 있습니다.

* *성능.*  Splunk SmartStore와 NetApp StorageGRID 결합하면 객체 스토리지를 사용하여 핫 버킷과 웜 버킷 간에 데이터를 빠르게 마이그레이션할 수 있습니다.  StorageGRID 대규모 객체 작업 부하에 대해 빠른 성능을 제공하여 마이그레이션 프로세스를 가속화합니다.
* *다중 사이트 준비 완료.*  StorageGRID 분산 아키텍처를 사용하면 Splunk SmartStore가 단일 글로벌 네임스페이스를 통해 단일 사이트와 여러 사이트에 배포를 확장할 수 있으며, 데이터가 어디에 있든 관계없이 모든 사이트에서 데이터에 액세스할 수 있습니다.
* *확장성이 향상되었습니다.*  Splunk 환경에서 변화하는 요구 사항과 수요를 충족하기 위해 컴퓨팅 리소스와 별도로 스토리지 리소스를 확장하여 TCO를 개선합니다.
* *용량.*  StorageGRID 사용하여 단일 네임스페이스를 560PB 이상으로 확장하여 Splunk 배포에서 빠르게 증가하는 볼륨을 처리하세요.
* *데이터 가용성.*  데이터의 비즈니스 가치가 변화함에 따라 동적으로 조정할 수 있는 메타데이터 기반 정책을 통해 데이터 가용성, 성능, 지리적 분포, 보존, 보호 및 저장 비용을 최적화하세요.


로컬(핫) 및 원격(웜) 스토리지 간 버킷 복사본 전송을 처리하는 인덱서의 구성 요소인 SmartStore 캐시를 사용하여 성능을 향상시킵니다.  이 솔루션에 대한 Splunk 크기 조정은 다음을 기반으로 합니다. https://docs.splunk.com/Documentation/Splunk/8.0.5/Capacity/Summaryofperformancerecommendations["Splunk에서 제공하는 가이드라인"^] .  이 솔루션을 사용하면 단일 및 다중 사이트 배포에서 사용자 수나 수집 속도 측면에서 증가하는 수요를 충족하기 위해 컴퓨팅, 핫 스토리지 또는 S3 리소스를 추가할 수 있습니다.
