---
sidebar: sidebar 
permalink: infra/ai-lenovo-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: AI 기반 자동화 및 엣지 컴퓨팅은 기업 조직이 디지털 전환을 달성하고 운영 효율성과 안전성을 극대화하는 데 도움이 되는 선도적인 접근 방식입니다.  엣지 컴퓨팅을 사용하면 데이터가 데이터 센터로 이동하거나 데이터 센터에서 전송되지 않으므로 훨씬 빠르게 처리됩니다.  따라서 데이터 센터나 클라우드로 데이터를 주고받는 데 드는 비용이 절감됩니다. 
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AI 기반 자동화 및 엣지 컴퓨팅은 기업 조직이 디지털 전환을 달성하고 운영 효율성과 안전성을 극대화하는 데 도움이 되는 선도적인 접근 방식입니다.  엣지 컴퓨팅을 사용하면 데이터가 데이터 센터로 이동하거나 데이터 센터에서 전송되지 않으므로 훨씬 빠르게 처리됩니다.  따라서 데이터 센터나 클라우드로 데이터를 주고받는 데 드는 비용이 절감됩니다.  기업이 엣지에 구축된 AI 추론 모델을 사용하여 거의 실시간으로 의사 결정을 내려야 하는 경우, 지연 시간을 줄이고 속도를 높이는 것이 유익할 수 있습니다.

NetApp 스토리지 시스템은 로컬 SSD 스토리지와 동일하거나 더 나은 성능을 제공하며 데이터 과학자, 데이터 엔지니어, AI/ML 개발자, 비즈니스 또는 IT 의사 결정권자에게 다음과 같은 이점을 제공합니다.

* AI 시스템, 분석 및 기타 중요 비즈니스 시스템 간에 데이터를 손쉽게 공유할 수 있습니다.  이러한 데이터 공유를 통해 인프라 오버헤드가 줄어들고, 성능이 향상되며, 기업 전체의 데이터 관리가 간소화됩니다.
* 비용을 최소화하고 리소스 사용을 개선하기 위해 독립적으로 확장 가능한 컴퓨팅 및 스토리지.
* 즉각적이고 공간 효율적인 사용자 작업 공간, 통합 버전 제어, 자동화된 배포를 위한 통합 스냅샷 복사본과 복제를 사용하여 개발 및 배포 워크플로를 간소화합니다.
* 재해 복구 및 비즈니스 연속성을 위한 엔터프라이즈급 데이터 보호.  이 문서에 소개된 NetApp 과 Lenovo 솔루션은 엣지에서 엔터프라이즈급 AI 추론을 배포하는 데 이상적인 유연하고 확장 가능한 아키텍처입니다.




== 감사의 말

* 제이제이  Falkanger, Lenovo HPC 및 AI 솔루션 수석 관리자
* Dave Arnette, NetApp 기술 마케팅 엔지니어
* Joey Parnell, NetApp E-Series AI 솔루션 기술 책임자
* 코디 해리먼, NetApp QA 엔지니어




== 추가 정보를 찾을 수 있는 곳

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 문서 및/또는 웹사이트를 참조하세요.

* NetApp AFF A-시리즈 어레이 제품 페이지
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* NetApp ONTAP 데이터 관리 소프트웨어 ONTAP 9 정보 라이브러리
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727: NetApp EF 시리즈 소개
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* NetApp E-시리즈 SANtricity 소프트웨어 데이터시트
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* 컨테이너용 NetApp 영구 스토리지 NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* NetApp BlueXP 복사 및 동기화
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* TensorFlow 벤치마크
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* 레노버 ThinkSystem SE350 엣지 서버
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* 레노버 ThinkSystem DM5100F 통합 플래시 스토리지 어레이
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


