---
sidebar: sidebar 
permalink: software/ai-conf-protopia-usecases.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: 디지털 이미지 처리에는 많은 장점이 있으며, 이를 통해 많은 조직이 시각적 표현과 관련된 데이터를 최대한 활용할 수 있습니다.  NetApp 과 Protopia 솔루션은 ML/DL 수명 주기 전반에 걸쳐 AI/ML 데이터를 보호하고 비공개화하는 고유한 AI 추론 설계를 제공합니다.  이를 통해 고객은 민감한 데이터의 소유권을 유지하고, 개인정보 보호와 관련된 우려를 완화하여 규모와 효율성을 위해 퍼블릭 또는 하이브리드 클라우드 배포 모델을 사용하고, 엣지에서 AI 추론을 배포할 수 있습니다. 
---
= 솔루션 영역
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
디지털 이미지 처리에는 많은 장점이 있으며, 이를 통해 많은 조직이 시각적 표현과 관련된 데이터를 최대한 활용할 수 있습니다.  NetApp 과 Protopia 솔루션은 ML/DL 수명 주기 전반에 걸쳐 AI/ML 데이터를 보호하고 비공개화하는 고유한 AI 추론 설계를 제공합니다.  이를 통해 고객은 민감한 데이터의 소유권을 유지하고, 개인정보 보호와 관련된 우려를 완화하여 규모와 효율성을 위해 퍼블릭 또는 하이브리드 클라우드 배포 모델을 사용하고, 엣지에서 AI 추론을 배포할 수 있습니다.



== 환경 지능

산업계에서는 환경적 위험 측면에서 지리공간 분석을 활용할 수 있는 다양한 방법이 있습니다.  정부와 공공사업부는 전염병이나 산불과 같은 자연재해 발생 시 대중에게 더 나은 조언을 제공하기 위해 공중 보건과 기상 상황에 대한 실행 가능한 통찰력을 얻을 수 있습니다.  예를 들어, 공항이나 병원과 같은 공공 장소에서 영향을 받은 개인의 사생활을 침해하지 않고 COVID-19 양성 환자를 식별하고 해당 당국과 주변 대중에게 필요한 안전 조치를 알릴 수 있습니다.



== 엣지 디바이스 웨어러블

군대와 전장에서 최첨단 AI 추론을 웨어러블 기기로 사용하여 군인의 건강을 추적하고, 운전자의 행동을 모니터링하고, 군용 차량에 접근하는 것과 관련된 안전 및 위험에 대해 당국에 경고하는 동시에 군인의 개인 정보를 보호하고 보존할 수 있습니다.  군대의 미래는 전장 사물 인터넷(IoBT)과 군사 사물 인터넷(IoMT)을 통해 첨단 기술로 전환되고 있으며, 이는 빠른 엣지 컴퓨팅을 사용하여 군인들이 적을 식별하고 전투에서 더 나은 성과를 낼 수 있도록 돕는 착용형 전투 장비를 의미합니다.  드론이나 웨어러블 장비와 같은 엣지 장치에서 수집된 시각적 데이터를 보호하고 보존하는 것은 해커와 적을 멀리하는 데 매우 중요합니다.



== 비전투원 대피 작전

비전투원 대피 작전(NEO)은 국방부가 수행하며, 생명이 위험한 미국 시민과 국민, 국방부 민간인, 지정된 사람(주재국(HN)과 제3국 국민(TCN))을 적절한 안전한 피난처로 대피시키는 것을 돕기 위해 수행됩니다.  시행 중인 행정 통제는 대부분 수동 대피자 심사 절차를 사용합니다.  그러나 대피자 식별, 대피자 추적, 위협 스크리닝의 정확성, 보안, 속도는 AI/ML 비디오 난독화 기술과 결합된 고도로 자동화된 AI/ML 도구를 사용하면 잠재적으로 개선될 수 있습니다.



== 의료 및 생물의학 연구

영상 처리란 컴퓨터 단층촬영(CT)이나 자기공명영상(MRI)으로부터 얻은 3D 영상을 바탕으로 수술 계획을 위한 병리학적 진단을 내리는 데 사용됩니다.  HIPAA 개인정보 보호 규칙은 조직이 모든 개인정보 및 사진과 같은 디지털 이미지에 대한 데이터를 수집, 처리 및 삭제하는 방법을 규정합니다.  HIPAA 안전 항구 규정에 따라 데이터가 공유 가능한 것으로 간주되려면 얼굴 전체가 나온 사진 이미지와 이와 비슷한 이미지를 삭제해야 합니다.  개인의 얼굴 특징을 구조적 CT/MR 이미지에서 가리는 데 사용되는 익명화나 두개골 제거 알고리즘과 같은 자동화된 기술은 생물의학 연구 기관의 데이터 공유 프로세스에 필수적인 부분이 되었습니다.



== AI/ML 분석의 클라우드 마이그레이션

기업 고객은 전통적으로 온프레미스에서 AI/ML 모델을 훈련하고 배포해 왔습니다.  규모의 경제와 효율성을 이유로 이러한 고객은 AI/ML 기능을 퍼블릭, 하이브리드 또는 멀티 클라우드 배포로 옮기는 방향으로 확장하고 있습니다.  그러나 다른 인프라에 노출될 수 있는 데이터에 따라 제한을 받습니다.  NetApp 솔루션은 필요한 모든 사이버 보안 위협을 해결합니다. https://www.netapp.com/data-protection/?internal_promo=mdw_aiml_ww_all_awareness-coas_blog["데이터 보호"^] 보안 평가를 수행하고 Protopia 데이터 변환과 결합하면 이미지 처리 AI/ML 워크로드를 클라우드로 마이그레이션하는 데 따른 위험을 최소화할 수 있습니다.

다른 산업 분야에서 엣지 컴퓨팅 및 AI 추론에 대한 추가 사용 사례는 다음을 참조하세요.link:../infra/ai-lenovo-edge-intro.html["TR-4886 엣지에서의 AI 추론"^] 그리고 NetApp AI 블로그, https://www.netapp.com/blog/federated-learning-intelligence-vs-privacy/["지능 대 개인 정보 보호"^] .
