---
sidebar: sidebar 
permalink: software/ai-conf-protopia-conclusion.html 
keywords: conclusion, ai inferencing, 
summary: 데이터는 저장 중, 전송 중, 컴퓨팅 중이라는 세 가지 상태로 존재합니다.  모든 AI 추론 서비스에서 중요한 부분은 전체 프로세스 동안 위협으로부터 데이터를 보호하는 것입니다.  추론 중에 데이터를 보호하는 것은 매우 중요합니다. 추론 과정에서 외부 고객과 추론 서비스를 제공하는 기업에 대한 개인 정보가 노출될 수 있기 때문입니다. 
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
데이터는 저장 중, 전송 중, 컴퓨팅 중이라는 세 가지 상태로 존재합니다.  모든 AI 추론 서비스에서 중요한 부분은 전체 프로세스 동안 위협으로부터 데이터를 보호하는 것입니다.  추론 중에 데이터를 보호하는 것은 매우 중요합니다. 추론 과정에서 외부 고객과 추론 서비스를 제공하는 기업에 대한 개인 정보가 노출될 수 있기 때문입니다.  Protopia AI는 오늘날 시장에서 기밀 AI 추론을 위한 눈에 띄지 않는 소프트웨어 전용 솔루션입니다.  Protopia를 사용하면 AI는 현재 AI/ML 작업을 수행하는 데 필수적인 데이터 레코드의 변환된 정보만 공급받고 그 이상은 공급받지 않습니다.  이러한 확률적 변환은 마스킹의 한 형태가 아니며, 큐레이트된 노이즈를 사용하여 데이터의 표현을 수학적으로 변경하는 데 기반을 둡니다.

ONTAP 기능을 갖춘 NetApp 스토리지 시스템은 로컬 SSD 스토리지와 동일하거나 더 나은 성능을 제공하며, NetApp DataOps Toolkit과 결합하면 데이터 과학자, 데이터 엔지니어, AI/ML 개발자, 비즈니스 또는 기업 IT 의사 결정권자에게 다음과 같은 이점을 제공합니다.

* AI 시스템, 분석 및 기타 중요 비즈니스 시스템 간에 데이터를 손쉽게 공유할 수 있습니다.  이러한 데이터 공유를 통해 인프라 오버헤드가 줄어들고, 성능이 향상되며, 기업 전체의 데이터 관리가 간소화됩니다.
* 비용을 최소화하고 리소스 사용을 개선하기 위해 독립적으로 확장 가능한 컴퓨팅 및 스토리지.
* 즉각적이고 공간 효율적인 사용자 작업 공간, 통합 버전 제어, 자동화된 배포를 위한 통합 스냅샷 복사본과 복제를 사용하여 개발 및 배포 워크플로를 간소화합니다.
* 재해 복구, 비즈니스 연속성 및 규정 요구 사항을 위한 엔터프라이즈급 데이터 보호 및 데이터 거버넌스.
* 데이터 관리 작업을 간편하게 호출할 수 있습니다. Jupyter Notebook의 NetApp DataOps Toolkit에서 데이터 과학자 작업 공간의 스냅샷 사본을 빠르게 가져와 백업하고 추적할 수 있습니다.


NetApp 및 Protopia 솔루션은 엔터프라이즈급 AI 추론 배포에 이상적인 유연하고 확장 가능한 아키텍처를 제공합니다.  이를 통해 데이터 보호가 가능해지고 민감한 정보에 대한 개인 정보 보호가 가능해져, 온프레미스와 하이브리드 클라우드 배포 모두에서 책임감 있는 AI 관행을 통해 기밀 AI 추론 요구 사항을 충족할 수 있습니다.
