---
sidebar: sidebar 
permalink: software/ai-hybrid-ddlnexus-setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, Hybrid, Hybrid Cloud, Hybrid Multicloud, Cloud, AWS, Amazon, Amazon Web Services, FSx ONTAP, FSx, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Domino Data Lab 및 NetApp 사용한 하이브리드 멀티클라우드 MLOps - 초기 설정 
---
= 초기 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 온프레미스 데이터 센터와 AWS를 통합한 하이브리드 환경에서 NetApp 데이터 서비스와 함께 Domino Nexus를 활용하기 위해 수행해야 하는 초기 설정 작업을 설명합니다.



== 필수 조건

이 섹션에 설명된 단계를 수행하기 전에 다음 작업을 이미 수행했다고 가정합니다.

* 온프레미스 NetApp ONTAP 스토리지 플랫폼을 이미 배포하고 구성했습니다. 자세한 내용은 다음을 참조하세요. link:https://www.netapp.com/support-and-training/documentation/["NetApp 제품 설명서"] .
* AWS에서 Amazon FSx ONTAP 인스턴스를 이미 프로비저닝했습니다. 자세한 내용은 다음을 참조하세요. link:https://aws.amazon.com/fsx/netapp-ontap/["Amazon FSx ONTAP 제품 페이지"] .
* 온프레미스 데이터 센터에 Kubernetes 클러스터를 이미 프로비저닝했습니다. 자세한 내용은 다음을 참조하세요. link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino 관리자 가이드"] .
* AWS에서 Amazon EKS 클러스터를 이미 프로비저닝했습니다. 자세한 내용은 다음을 참조하세요. link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino 관리자 가이드"] .
* 온프레미스 Kubernetes 클러스터에 NetApp Trident 설치했습니다.  또한, 스토리지 리소스를 프로비저닝하고 관리할 때 온프레미스 NetApp ONTAP 스토리지 플랫폼을 사용하도록 이 Trident 인스턴스를 구성했습니다. 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident 설명서"] .
* Amazon EKS 클러스터에 NetApp Trident 설치했습니다.  또한 스토리지 리소스를 프로비저닝하고 관리할 때 Amazon FSx ONTAP 인스턴스를 사용하도록 이 Trident 인스턴스를 구성했습니다. 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident 설명서"] .
* 온프레미스 데이터 센터와 AWS의 Virtual Private Cloud(VPC) 간에 양방향 네트워크 연결이 있어야 합니다.  이를 구현하기 위한 다양한 옵션에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html["Amazon 가상 사설망(VPN) 설명서"] .




== AWS에 Domino Enterprise AI Platform 설치

AWS에 Domino Enterprise MLOps 플랫폼을 설치하려면 다음 지침을 따르세요.link:https://docs.dominodatalab.com/en/latest/admin_guide/c1eec3/deploy-domino/["Domino 관리자 가이드"] .  이전에 프로비저닝한 것과 동일한 Amazon EKS 클러스터에 Domino를 배포해야 합니다.  또한, NetApp Trident 이 EKS 클러스터에 이미 설치 및 구성되어 있어야 하며, domino.yml 설치 구성 파일에서 공유 스토리지 클래스로 Trident 관리 스토리지 클래스를 지정해야 합니다.


NOTE: 를 참조하세요link:https://docs.dominodatalab.com/en/latest/admin_guide/7f4331/install-configuration-reference/#storage-classes["Domino 설치 구성 참조 가이드"] domino.yml 설치 구성 파일에서 공유 저장소 클래스를 지정하는 방법에 대한 자세한 내용은 다음을 참조하세요.


NOTE: link:https://www.netapp.com/media/79922-tr-4952.pdf["기술 보고서 TR-4952"]Amazon FSx ONTAP 사용하여 AWS에 Domino를 배포하는 과정을 안내하며, 발생하는 문제를 해결하는 데 유용한 참고 자료가 될 수 있습니다.



== Domino Nexus 활성화

다음으로 Domino Nexus를 활성화해야 합니다.  를 참조하세요link:https://docs.dominodatalab.com/en/latest/admin_guide/c65074/nexus-hybrid-architecture/["Domino 관리자 가이드"] 자세한 내용은.



== 온프레미스 데이터 센터에 Domino 데이터 플레인 배포

다음으로, 온프레미스 데이터 센터에 Domino 데이터 플레인을 배포해야 합니다.  이전에 프로비저닝한 온프레미스 Kubernetes 클러스터에 이 데이터 플레인을 배포해야 합니다.  또한 NetApp Trident 이 Kubernetes 클러스터에 이미 설치 및 구성되어 있어야 합니다.  를 참조하세요link:https://docs.dominodatalab.com/en/latest/admin_guide/5781ea/data-planes/["Domino 관리자 가이드"] 자세한 내용은.
