---
sidebar: sidebar 
permalink: software/ai-nvaie-vmw-tech.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NetApp 및 VMware를 활용한 NVIDIA AI Enterprise - 기술 개요 
---
= 기술 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 NetApp 및 VMware를 기반으로 한 NVIDIA AI Enterprise에 대한 기술 개요를 제공합니다.



== NVIDIA AI 엔터프라이즈

NVIDIA AI Enterprise는 NVIDIA 인증 시스템을 통해 VMware vSphere에서 실행되도록 NVIDIA 에서 최적화, 인증 및 지원하는 엔드 투 엔드 클라우드 기반 AI 및 데이터 분석 소프트웨어 제품군입니다.  이 소프트웨어는 최신 하이브리드 클라우드 환경에서 AI 워크로드를 간단하고 빠르게 배포, 관리, 확장할 수 있도록 지원합니다.



== NVIDIA GPU 클라우드(NGC)

NVIDIA NGC는 AI 실무자가 AI 솔루션을 개발할 수 있도록 GPU 최적화 소프트웨어 카탈로그를 호스팅합니다.  또한 모델 학습을 위한 NVIDIA Base Command, 모델 배포 및 모니터링을 위한 NVIDIA Fleet Command, 독점 AI 소프트웨어에 안전하게 액세스하고 관리하기 위한 NGC Private Registry 등 다양한 AI 서비스에 대한 액세스를 제공합니다.  또한 NVIDIA AI Enterprise 고객은 NGC 포털을 통해 지원을 요청할 수 있습니다.



== VMware vSphere

VMware vSphere는 VMware의 가상화 플랫폼으로, 데이터 센터를 CPU, 스토리지 및 네트워킹 리소스를 포함하는 통합 컴퓨팅 인프라로 변환합니다. vSphere는 이러한 인프라를 통합 운영 환경으로 관리하고, 관리자에게 해당 환경에 참여하는 데이터 센터를 관리할 수 있는 도구를 제공합니다.

vSphere의 두 가지 핵심 구성 요소는 ESXi와 vCenter Server입니다.  ESXi는 관리자가 가상 머신과 가상 어플라이언스를 생성하고 실행하는 가상화 플랫폼입니다. vCenter Server는 관리자가 네트워크에 연결된 여러 호스트를 관리하고 호스트 리소스를 풀링하는 서비스입니다.



== NetApp ONTAP

NetApp 의 최신 스토리지 관리 소프트웨어인 ONTAP 9를 사용하면 기업이 인프라를 현대화하고 클라우드 지원 데이터 센터로 전환할 수 있습니다.  ONTAP 업계 최고의 데이터 관리 역량을 활용하여 데이터가 어디에 있든 단일 도구 세트를 사용하여 데이터를 관리하고 보호할 수 있도록 지원합니다.  또한 필요한 곳, 즉 엣지, 코어, 클라우드로 데이터를 자유롭게 이동할 수 있습니다.  ONTAP 9에는 데이터 관리를 간소화하고, 중요 데이터를 가속화하고 보호하며, 하이브리드 클라우드 아키텍처 전반에서 차세대 인프라 기능을 구현하는 다양한 기능이 포함되어 있습니다.



=== 데이터 관리 간소화

적절한 리소스가 AI 애플리케이션과 AI/ML 데이터 세트 교육에 사용될 수 있도록 기업 IT 운영과 데이터 과학자에게 데이터 관리가 매우 중요합니다.  NetApp 기술에 대한 다음 추가 정보는 이 검증 범위를 벗어나지만 배포에 따라 관련이 있을 수 있습니다.

ONTAP 데이터 관리 소프트웨어에는 다음과 같은 기능이 포함되어 있어 운영을 간소화하고 단순화하며 총 운영 비용을 절감할 수 있습니다.

* 인라인 데이터 압축 및 확장된 중복 제거.  데이터 압축은 저장 블록 내부의 낭비되는 공간을 줄이고, 중복 제거는 효과적인 용량을 크게 증가시킵니다.  이는 로컬에 저장된 데이터와 클라우드에 계층화된 데이터 모두에 적용됩니다.
* 최소, 최대 및 적응형 서비스 품질(AQoS).  세분화된 서비스 품질(QoS) 제어는 공유 빈도가 높은 환경에서 중요한 애플리케이션의 성능 수준을 유지하는 데 도움이 됩니다.
* NetApp FabricPool.  Amazon Web Services(AWS), Azure, NetApp StorageGRID 스토리지 솔루션을 포함한 퍼블릭 및 프라이빗 클라우드 스토리지 옵션에 콜드 데이터의 자동 계층화를 제공합니다.  FabricPool 에 대한 자세한 내용은 다음을 참조하세요. https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598: FabricPool 모범 사례"^] .




=== 데이터 가속화 및 보호

ONTAP 뛰어난 수준의 성능과 데이터 보호 기능을 제공하며 다음과 같은 방식으로 이러한 기능을 확장합니다.

* 성능과 낮은 지연 시간.  ONTAP 가능한 가장 낮은 지연 시간으로 가능한 가장 높은 처리량을 제공합니다.
* 데이터 보호.  ONTAP 모든 플랫폼에서 공통적으로 관리할 수 있는 내장형 데이터 보호 기능을 제공합니다.
* NetApp 볼륨 암호화(NVE).  ONTAP 온보드 및 외부 키 관리 지원을 통해 기본 볼륨 수준 암호화를 제공합니다.
* 다중 테넌시 및 다중 요소 인증.  ONTAP 최고 수준의 보안을 통해 인프라 리소스를 공유할 수 있도록 합니다.




=== 미래 지향적 인프라

ONTAP 다음과 같은 기능을 통해 까다롭고 끊임없이 변화하는 비즈니스 요구 사항을 충족하는 데 도움이 됩니다.

* 원활한 확장과 중단 없는 운영.  ONTAP 기존 컨트롤러와 확장형 클러스터에 중단 없이 용량을 추가할 수 있도록 지원합니다.  고객은 비용이 많이 드는 데이터 마이그레이션이나 중단 없이 NVMe 및 32Gb FC와 같은 최신 기술로 업그레이드할 수 있습니다.
* 클라우드 연결.  ONTAP 모든 퍼블릭 클라우드에서 소프트웨어 정의 스토리지(ONTAP Select)와 클라우드 기반 인스턴스(Google Cloud NetApp Volumes)에 대한 옵션을 제공하는 가장 클라우드에 연결된 스토리지 관리 소프트웨어입니다.
* 새로운 애플리케이션과의 통합.  ONTAP 기존 엔터프라이즈 앱을 지원하는 동일한 인프라를 사용하여 자율주행차, 스마트 시티, 산업 4.0과 같은 차세대 플랫폼과 애플리케이션을 위한 엔터프라이즈급 데이터 서비스를 제공합니다.




== NetApp DataOps 툴킷

NetApp DataOps Toolkit은 고성능, 확장형 NetApp 스토리지에 의해 지원되는 개발/교육 작업 공간과 추론 서버의 관리를 간소화하는 Python 기반 도구입니다.  주요 기능은 다음과 같습니다.

* 고성능, 확장형 NetApp 스토리지로 지원되는 새로운 대용량 JupyterLab 작업 공간을 빠르게 프로비저닝하세요.
* 엔터프라이즈급 NetApp 스토리지로 지원되는 새로운 NVIDIA Triton Inference Server 인스턴스를 빠르게 프로비저닝하세요.
* 실험이나 빠른 반복을 가능하게 하기 위해 대용량 JupyterLab 작업 공간을 거의 즉각적으로 복제합니다.
* 대용량 JupyterLab 작업 공간의 스냅샷을 거의 즉각적으로 저장하여 백업 및/또는 추적/기준 설정을 할 수 있습니다.
* 거의 즉각적으로 대용량, 고성능 데이터 볼륨을 프로비저닝, 복제 및 스냅샷합니다.

