---
sidebar: sidebar 
permalink: software/ai-osmlops-trident-ops.html 
keywords: Trident 
summary: NetApp 사용한 오픈 소스 MLOps - Trident Operations 예시 
---
= Trident 작업 예시
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에는 Trident 사용하여 수행할 수 있는 다양한 작업의 예가 포함되어 있습니다.



== 기존 볼륨 가져오기

Kubernetes 클러스터 내의 컨테이너에 마운트하려는 NetApp 스토리지 시스템/플랫폼에 기존 볼륨이 있지만 해당 볼륨이 클러스터의 PVC에 연결되지 않은 경우 해당 볼륨을 가져와야 합니다.  Trident 볼륨 가져오기 기능을 사용하면 이러한 볼륨을 가져올 수 있습니다.

다음 예제 명령은 이름이 지정된 볼륨을 가져오는 방법을 보여줍니다. `pb_fg_all` .  PVC에 대한 자세한 내용은 다음을 참조하세요. https://kubernetes.io/docs/concepts/storage/persistent-volumes/["공식 Kubernetes 문서"^] .  볼륨 가져오기 기능에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/trident/index.html["Trident 문서"^] .

안 `accessModes` 의 가치 `ReadOnlyMany` 예제 PVC 사양 파일에 지정되어 있습니다.  자세한 내용은 `accessMode` 필드에서 확인하세요 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["공식 Kubernetes 문서"^] .

....
$ cat << EOF > ./pvc-import-pb_fg_all-iface1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface1
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface1
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface1 pb_fg_all -f ./pvc-import-pb_fg_all-iface1.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1 | 10 TiB | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ tridentctl get volume -n trident
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
|               NAME               |  SIZE   |           STORAGE CLASS           | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1   | 10 TiB  | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
$ kubectl get pvc
NAME                 STATUS   VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1     Bound    default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   25h
....


== 새 볼륨 제공

Trident 사용하면 NetApp 스토리지 시스템이나 플랫폼에 새 볼륨을 프로비저닝할 수 있습니다.



=== kubectl을 사용하여 새 볼륨 프로비저닝

다음 예제 명령은 kubectl을 사용하여 새로운 FlexVol volume 프로비저닝하는 방법을 보여줍니다.

안 `accessModes` 의 가치 `ReadWriteMany` 다음 예제 PVC 정의 파일에 지정되어 있습니다.  자세한 내용은 `accessMode` 필드에서 확인하세요 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["공식 Kubernetes 문서"^] .

....
$ cat << EOF > ./pvc-tensorflow-results.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-ai-flexvols-retain
EOF
$ kubectl create -f ./pvc-tensorflow-results.yaml
persistentvolumeclaim/tensorflow-results created
$ kubectl get pvc
NAME                              STATUS    VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1                  Bound     default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   26h
tensorflow-results                Bound     default-tensorflow-results-2fd60   1073741824       RWX            ontap-ai-flexvols-retain            25h
....


=== NetApp DataOps 툴킷을 사용하여 새 볼륨 프로비저닝

Kubernetes용 NetApp DataOps Toolkit을 사용하여 NetApp 스토리지 시스템이나 플랫폼에 새 볼륨을 프로비저닝할 수도 있습니다.  Kubernetes용 NetApp DataOps Toolkit은 Trident 사용하여 볼륨을 프로비저닝하지만 사용자를 위해 프로세스를 간소화합니다.  를 참조하세요link:https://github.com/NetApp/netapp-dataops-toolkit/blob/main/netapp_dataops_k8s/docs/volume_management.md["선적 서류 비치"] 자세한 내용은.
