---
sidebar: sidebar 
permalink: software/ai-osmlops-architecture.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: NetApp 사용한 오픈 소스 MLOps - 아키텍처 
---
= 아키텍처
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 솔루션은 특정 하드웨어에 의존하지 않습니다.  이 솔루션은 NetApp Trident 가 지원하는 모든 NetApp 물리적 스토리지 어플라이언스, 소프트웨어 정의 인스턴스 또는 클라우드 서비스와 호환됩니다.  예로는 NetApp AFF 스토리지 시스템, Amazon FSx ONTAP, Azure NetApp Files, Google Cloud NetApp Volumes 또는 NetApp Cloud Volumes ONTAP 인스턴스가 있습니다.  또한, NetApp Trident 와 구현 중인 다른 솔루션 구성 요소에서 지원되는 Kubernetes 버전을 사용하는 한 모든 Kubernetes 클러스터에서 솔루션을 구현할 수 있습니다.  Trident 에서 지원하는 Kubernetes 버전 목록은 다음을 참조하세요. https://docs.netapp.com/us-en/trident/index.html["Trident 문서"^] .  이 솔루션의 다양한 구성 요소를 검증하는 데 사용된 환경에 대한 자세한 내용은 다음 표를 참조하세요.



== Apache Airflow 검증 환경

|===
| 소프트웨어 구성 요소 | 버전 


| 아파치 에어플로우 | 2.0.1, 다음을 통해 배포됨link:https://artifacthub.io/packages/helm/airflow-helm/airflow["Apache Airflow Helm 차트"^] 8.0.8 


| 쿠버네티스 | 1.18 


| NetApp Trident | 21.01 
|===


== JupyterHub 검증 환경

|===
| 소프트웨어 구성 요소 | 버전 


| 주피터허브 | 4.1.5, 배포됨link:https://hub.jupyter.org/helm-chart/["JupyterHub Helm 차트"^] 3.3.7 


| 쿠버네티스 | 1.29 


| NetApp Trident | 24.02 
|===


== MLflow 검증 환경

|===
| 소프트웨어 구성 요소 | 버전 


| ML플로우 | 2.14.1, 다음을 통해 배포됨link:https://artifacthub.io/packages/helm/bitnami/mlflow["MLflow Helm 차트"^] 1.4.12 


| 쿠버네티스 | 1.29 


| NetApp Trident | 24.02 
|===


== Kubeflow 검증 환경

|===
| 소프트웨어 구성 요소 | 버전 


| 쿠베플로우 | 1.7, 배포를 통해link:https://www.deploykf.org["배포KF"^] 0.1.1 


| 쿠버네티스 | 1.26 


| NetApp Trident | 23.07 
|===


== 지원하다

NetApp Apache Airflow, JupyterHub, MLflow, Kubeflow 또는 Kubernetes에 대한 엔터프라이즈 지원을 제공하지 않습니다.  완벽하게 지원되는 MLOps 플랫폼에 관심이 있으시다면,link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["NetApp 에 문의하세요"^] NetApp 파트너와 함께 제공하는 완벽하게 지원되는 MLOps 솔루션에 대해 알아보세요.
