---
sidebar: sidebar 
permalink: vector-db/ai-vdb-conclusion.html 
keywords: vector database, conclusion 
summary: 결론 - NetApp을 위한 벡터 데이터베이스 솔루션 
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 NetApp 의 벡터 데이터베이스 솔루션을 마무리합니다.



== 결론

결론적으로, 이 문서는 NetApp 스토리지 솔루션에서 Milvus 및 pgvector와 같은 벡터 데이터베이스를 배포하고 관리하는 방법에 대한 포괄적인 개요를 제공합니다.  NetApp ONTAP 및 StorageGRID 객체 스토리지를 활용하기 위한 인프라 가이드라인을 논의하고 파일 및 객체 저장소를 통해 AWS FSx ONTAP 에서 Milvus 데이터베이스를 검증했습니다.

우리는 NetApp의 파일-객체 이중성을 살펴보고 벡터 데이터베이스의 데이터뿐만 아니라 다른 애플리케이션에도 유용하다는 것을 보여주었습니다.  또한 NetApp의 엔터프라이즈 관리 제품인 SnapCenter 벡터 데이터베이스 데이터에 대한 백업, 복원 및 복제 기능을 제공하여 데이터 무결성과 가용성을 보장하는 방식도 강조했습니다.

또한 이 문서에서는 NetApp의 하이브리드 클라우드 솔루션이 온프레미스 및 클라우드 환경에서 데이터 복제 및 보호를 제공하여 원활하고 안전한 데이터 관리 환경을 제공하는 방법을 자세히 설명합니다.  우리는 NetApp ONTAP 에서 Milvus와 pgvecto와 같은 벡터 데이터베이스의 성능 검증에 대한 통찰력을 제공하고, 이러한 데이터베이스의 효율성과 확장성에 대한 귀중한 정보를 제공했습니다.

마지막으로 LLM을 활용한 RAG와 NetApp의 내부 ChatAI라는 두 가지 생성 AI 사용 사례에 대해 논의했습니다.  이러한 실제 사례는 이 문서에 설명된 개념과 관행의 실제 적용과 이점을 강조합니다.  전반적으로 이 문서는 벡터 데이터베이스를 관리하기 위해 NetApp의 강력한 스토리지 솔루션을 활용하고자 하는 모든 사람을 위한 포괄적인 가이드 역할을 합니다.



=== 감사의 말

저자는 아래의 기여자들과 NetApp 고객과 NetApp 분야에 귀중한 이 논문을 만들기 위해 피드백과 의견을 제공해주신 분들께 진심으로 감사드리고 싶습니다.

. Sathish Thyagarajan, NetApp ONTAP AI 및 분석 기술 마케팅 엔지니어
. Mike Oglesby, NetApp 기술 마케팅 엔지니어
. AJ Mahajan, NetApp 수석 이사
. Joe Scott, NetApp 워크로드 성능 엔지니어링 관리자
. Puneet Dhawan, NetApp Fsx 제품 관리 부문 수석 이사
. Yuval Kalderon, NetApp FSx 제품 팀 수석 제품 관리자




=== 추가 정보를 찾을 수 있는 곳

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 문서 및/또는 웹사이트를 검토하세요.

* Milvus 문서 - https://milvus.io/docs/overview.md[]
* Milvus 독립형 문서 - https://milvus.io/docs/v2.0.x/install_standalone-docker.md[]
* NetApp 제품 문서https://www.netapp.com/support-and-training/documentation/[]
* 인스타클러스트 -link:https://www.instaclustr.com/support/documentation/?_bt=&_bk=&_bm=&_bn=x&_bg=&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=1467100120&hsa_cam=20766399079&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAjw26KxBhBDEiwAu6KXtzOZhN0dl0H1smOMcj9nsC0qBQphdMqFR7IrVQqeG2Y4aHWydUMj2BoCdFwQAvD_BwE["설치 클러스터 문서"]




=== 버전 기록

|===


| 버전 | 날짜 | 문서 버전 기록 


| 버전 1.0 | 2024년 4월 | 최초 출시 
|===