---
sidebar: sidebar 
permalink: vector-db/ai-vdb-intro.html 
keywords: vector database 
summary: NetApp용 벡터 데이터베이스 솔루션 소개 
---
= 소개
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 NetApp 용 벡터 데이터베이스 솔루션을 소개합니다.



== 소개

벡터 데이터베이스는 대규모 언어 모델(LLM)과 생성형 인공 지능(AI)에서 의미 검색의 복잡성을 처리하도록 설계된 과제를 효과적으로 해결합니다.  기존 데이터 관리 시스템과 달리 벡터 데이터베이스는 레이블이나 태그가 아닌 데이터 자체의 내용을 사용하여 이미지, 비디오, 텍스트, 오디오 및 기타 형태의 비정형 데이터를 포함한 다양한 유형의 데이터를 처리하고 검색할 수 있습니다.

관계형 데이터베이스 관리 시스템(RDBMS)의 한계는 잘 알려져 있으며, 특히 AI 애플리케이션에서 흔히 볼 수 있는 고차원 데이터 표현과 비정형 데이터 처리의 어려움에 대한 내용이 많습니다.  RDBMS는 데이터를 관리하기 쉬운 구조로 평면화하는 데 시간이 많이 걸리고 오류가 발생하기 쉬운 프로세스를 필요로 하며, 이로 인해 검색이 지연되고 비효율적이 됩니다.  그러나 벡터 데이터베이스는 이러한 문제를 해결하도록 설계되어 복잡하고 고차원 데이터를 관리하고 검색하기 위한 보다 효율적이고 정확한 솔루션을 제공함으로써 AI 애플리케이션의 발전을 촉진합니다.

이 문서는 현재 벡터 데이터베이스를 사용 중이거나 사용할 계획인 고객을 위한 포괄적인 가이드로, NetApp ONTAP, NetApp StorageGRID, Amazon FSx ONTAP for NetApp ONTAP, SnapCenter 등의 플랫폼에서 벡터 데이터베이스를 활용하는 모범 사례를 자세히 설명합니다.  여기에 제공된 내용은 다음과 같은 다양한 주제를 다룹니다.

* NetApp ONTAP 및 StorageGRID 개체 스토리지를 통해 NetApp 스토리지에서 제공하는 Milvus와 같은 벡터 데이터베이스에 대한 인프라 가이드라인입니다.
* 파일 및 객체 저장소를 통해 AWS FSx ONTAP 에서 Milvus 데이터베이스를 검증합니다.
* NetApp의 파일-객체 이중성을 탐구하여 벡터 데이터베이스와 기타 애플리케이션의 데이터에 대한 유용성을 보여줍니다.
* NetApp의 데이터 보호 관리 제품인 SnapCenter 는 벡터 데이터베이스 데이터에 대한 백업 및 복원 기능을 제공합니다.
* NetApp의 하이브리드 클라우드가 온프레미스 및 클라우드 환경 전반에서 데이터 복제 및 보호를 제공하는 방식입니다.
* NetApp ONTAP 에서 Milvus 및 pgvector와 같은 벡터 데이터베이스의 성능 검증에 대한 통찰력을 제공합니다.
* 두 가지 구체적인 사용 사례: 대규모 언어 모델(LLM)을 사용한 검색 증강 생성(RAG)과 NetApp IT 팀의 ChatAI를 통해 설명된 개념과 관행에 대한 실제적 예를 제공합니다.

